apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      creationTimestamp: null
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: wakalubiubiu/httpserver:v0.2-metrics
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: GO_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: httpserver-config
                  key: level
            - name: GO_PORT
              valueFrom:
                configMapKeyRef:
                  name: httpserver-config
                  key: port
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: httpserver-config
                  key: version
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30